[project]
name = "dafny-mcp"
version = "0.1.0"
description = "A MCP server for Dafny"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
    "fastmcp>=2.12.4",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
