name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install uv
        run: python -m pip install --upgrade pip && pip install uv

      - name: uv sync (install deps)
        run: uv lock || true && uv sync

      - name: Run tests
        run: uv run pytest -q
